server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8889/limayrac
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://limayrac-auth-server:9000